apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
  type: LoadBalancer
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_USERNAME: cG9zdGdyZXM=  # 'postgres' en base64
  DB_PASSWORD: UHVjZW0uMjAyNA==  # 'Pucem.2024' en base64
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: db-config
data:
  DB_HOST: "examen-enrique.postgres.database.azure.com"
  DB_PORT: "5432"
  DB_DATABASE: "postgres"
  DB_SSL: "true"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: christianencalada/examen-backend:latest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: db-credentials
            - configMapRef:
                name: db-config